[package]
edition = "2021"

name = "vsmtp-rule-engine"
version = "1.4.0-rc.5"
license = "GPL-3.0-only"

rust-version = "1.63.0"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-rule-engine/"

keywords = [
  "vsmtp",
  "scripting-engine",
  "scripting-language",
  "scripting",
  "rhai",
]
categories = ["config"]

[package.metadata.release]
pre-release-replacements = [
  { file = "Cargo.toml", prerelease = true, search = "common\\]\nversion = .*", replace = "common]\nversion = \"={{version}}\"" },
  { file = "Cargo.toml", prerelease = true, search = "config\\]\nversion = .*", replace = "config]\nversion = \"={{version}}\"" },
  { file = "Cargo.toml", prerelease = true, search = "auth\\]\nversion = .*", replace = "auth]\nversion = \"={{version}}\"" },
  { file = "Cargo.toml", prerelease = true, search = "mail-parser\\]\nversion = .*", replace = "mail-parser]\nversion = \"={{version}}\"" },
  { file = "Cargo.toml", prerelease = true, search = "vqueue\\]\nversion = .*", replace = "vqueue]\nversion = \"={{version}}\"" },
]

[dependencies.vsmtp-common]
version = "=1.4.0-rc.5"
path = "../vsmtp-common"

[dependencies.vsmtp-config]
version = "=1.4.0-rc.5"
path = "../vsmtp-config"

[dependencies.vsmtp-mail-parser]
version = "=1.4.0-rc.5"
path = "../vsmtp-mail-parser"

[dependencies.vsmtp-auth]
version = "=1.4.0-rc.5"
path = "../vsmtp-auth"

[dependencies.vqueue]
version = "=1.4.0-rc.5"
path = "../../vqueue"

[dependencies]

# Plugins
vsmtp-plugin-vsl = { path = "../plugins/vsmtp-plugin-vsl", version = "1.4.0-rc.5" }
rhai-dylib = { version = "0.1.4", features = ["sync"] }
rhai = { version = "1.11.0", features = [
  "unchecked",
  "sync",
  "internals",
  "no_closure",
  "metadata",
] }
tracing = { version = "0.1.37", default-features = false, features = [
  "std",
  "attributes",
  "release_max_level_info",
] }

anyhow = { version = "1.0.66", default-features = false, features = ["std"] }

thiserror = { version = "1.0.37", default-features = false }

either = { version = "1.8.0", default-features = false, features = ["use_std"] }

strum = { version = "0.24.1", default-features = false, features = [
  "std",
  "derive",
] }
serde_with = { version = "2.1.0", default-features = false, features = [
  "std",
  "macros",
] }


serde_json = { version = "1.0.89", default-features = false, features = [
  "std",
] }
serde = { version = "1.0.149", default-features = false, features = [
  "std",
  "derive",
] }
lettre = { version = "0.10.0", default-features = false, features = [
  "smtp-transport",
  "builder",
  "tokio1-rustls-tls",
  "tracing",
  "pool",
] }

wait-timeout = { version = "0.2.0", default-features = false }
users = { version = "0.11.0", default-features = false }

hostname = { version = "0.3.1", default-features = false }
time = { version = "0.3.17", default-features = false, features = [
  "std",
  "formatting",
  "macros",
] }

trust-dns-resolver = { version = "0.22.0", default-features = false, features = [
  "system-config",
  "tokio-runtime",
] }

tokio = { version = "1.23.0", default-features = false, features = [
  "macros",
  "sync",
  "fs",
  "libc",
  "mio",
  "rt-multi-thread",
] }
humantime-serde = { version = "1.1.1", default-features = false }

uuid = { version = "1.2.2", default-features = false, features = [
  "std",
  "v4",
  "fast-rng",
] }

[features]
default = ["delegation"]
delegation = []          # Add the delegation system.

[dev-dependencies]
vsmtp-test = { path = "../vsmtp-test" }
pretty_assertions = "1.3.0"
rstest = "0.16.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rsa = { version = "0.6.1", default-features = false, features = [
  "std",
  "pem",
  # "serde" # TODO
] }
