version: "3.9"

services:
  vsmtp:
    image: viridit/vsmtp:unstable
    hostname: vsmtp.example.tld
    volumes:
      - ./vsmtp-conf/vsmtp.vsl:/etc/vsmtp/vsmtp.vsl:ro
      - ./vsmtp-conf/clamsmtp.vsl:/etc/vsmtp/clamsmtp.vsl:ro
      - ./vsmtp-conf/filter.vsl:/etc/vsmtp/filter.vsl:ro
      - ./out:/var/spool/vsmtp:rw
    ports:
      - 127.0.0.1:10035:25
      - 127.0.0.1:10025:10025
    networks:
      example:
        ipv4_address: 10.5.0.5
    user: root

  clamsmtp:
    build:
      context: ./clamav-docker
      dockerfile: clamsmtp.Dockerfile
    hostname: clamsmtp.example.tld
    ports:
      - 127.0.0.1:10026:10026
    networks:
      - example
    volumes:
      - clamav-cache:/var/spool/clamsmtp/:rw
    depends_on:
      clamav:
        condition: service_healthy

  clamav:
    build:
      context: ./clamav-docker
      dockerfile: clamav.Dockerfile
    hostname: av.example.tld
    volumes:
      - clamav-cache:/var/spool/clamsmtp/:rw
    networks:
      - example
    ports:
      - 13310:3310
    environment:
      - CLAMAV_NO_FRESHCLAMD=true
    healthcheck:
      test: sh -c "[[ \"$(echo PING | nc localhost 3310)\" = \"PONG\" ]] || exit 1"
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

volumes:
  vsmtp:
  clamav-cache:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"

networks:
  example:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
